language: node_js
node_js: 
 - "5.10.1"
before_install:
 - "git submodule init && git submodule update"
 - "npm install"
notifications:
 - slack: travisci: WrZC6AK2axk6c60pHwf0dPlH
services:
 - postgresql
before_script:
 - psql -c "CREATE USER crudtest WITH PASSWORD 'crudtest';" -U postgres
 - psql -c 'create database crudtest;' -U crudtest -W crudtest
env:
 - DATABASE_URL=postgres://crudtest:crudtest@localhost/crudtest

