language: node_js
services:
 - postgresql
node_js: 
 - "5.10.1"
postgresql:
 - "9.4"
before_install:
 - "./install.sh"
notifications:
 - slack: 'devops-training-spb:WrZC6AK2axk6c60pHwf0dPlH#general'
env:
 - DATABASE_URL=postgres://crudtest:crudtest@localhost/crudtest

