language: node_js
services:
- postgresql
node_js:
- 5.10.1
addons:
  postgresql: '9.4'
before_script:
- bash install.sh
script:
- source env.sh && npm run test
notifications:
  slack: devops-training-spb:WrZC6AK2axk6c60pHwf0dPlH
deploy:
  api_key:
    secure: skB04sTDYqXrNrgpcwHPydg/c+Wa+OZOJevMSy8Y5IwMeRq2qSz++xY/X3GHTyoNTwZvcpHOPqnOcx+jB9DHPwjumgT4XQZ25KKEjjXEoiv4jdO7g7y//dtVZUsOhwM0vEmShJHLTbWvH/RrltNU+5J+DRfUe1UWZrDvOU6As2v1Dx47XtaoLnEYGcUf3Y+N4QDln+NoukCqHufjz9853uArilkwvCwG0Nm6Jzji+ANe+UxrsOoXeijneIAY0qqHN07T0wU1mhcvJOC+NsU3zLjmiPawxrI+wBNePVp/FBi9qNBdXZPL7+uJ3mhnZPDAXOngTh5GLC22iR9mWss4bH9XYexnUIQicXvTG+cfkJRmZxwN0jCLREhl/qD1KES2rD837LwT/H0622LQXdeJ58TCyZf5fIfDIcYnA2lTNnP1d1qwgvzwq1lsz5B0GV1pDLSNEwh8vqgJbTxihA1Jm57KxJdcByut0iplI056nqk4JJa4gK8BHWUnqrl8FZUmEH2xwgQEXGHL3C6nr83A5nRytQ9VWgQQA+SYNMimRbzGO8imLT0uZ+VMZB/6H9JmhRqY/tBWFsOx08k43qQ2YDsnkzh2+GTA70t92jDybxRWgxPqjNbazRykRBlPiQNsBt3P2hU12WGjGw7gmerXGVrVq8+FUgUgvMP6mzyYeW0=
