language: node_js
services:
- postgresql
node_js:
- 5.10.1
addons:
  postgresql: '9.4'
before_script:
- bash install.sh
script:
- source env.sh && npm run test
notifications:
  slack: devops-training-spb:WrZC6AK2axk6c60pHwf0dPlH
deploy:
  provider: heroku
  api_key:
    secure: tRGXaW5UZ9LepvvI2brBZVvhkrdHZn3I2Xf+U30NHGOAUNCQ8wlYc1cTBlHYweGpfBv3MAGMgZIfAFdijByFxbWqgYaKb0Kcn2j1fanwnJ5OQF+W7SioTm61EPX8qcEjWXGGfBd6/nUtIelJHum1IqipJ6hHAk/lL3EEd8CLNPI7Lw78kccFSw35Rg2UzBmFUqYjbU3pq7sgkz8eM3Im6RHntlbYi+wi19wcRrX5aBxELJrU1MOejMgEh+F33gt1TFliIGaYqFcS1oTKkeEjS8a/mgsEuxyL6+m4cT8olq55C63GupwnKe0PKb3emAEsJ7Zly+M4jR9pgeInOYk4vjx51BvrlPqZtUQ/hTAm6V/ZGUHdlbcCY91KRxALesS23be7I/JESTP3DPnUxUJTT8OcwZ092oTaUWIe15YiS9kOpOEPjK7Iu03cB7vBrbzi9PT2G4Zmbc3+5XHT51UYVquLRNTwXvhX+VOur2y4yQpd/pmk0JpG7GEsvYUqUdR16bg2NNtZ8qfSXOiAs8DXkz05D788QtZDcpW2LPGxJvLjd4lsAQZvUlYcmm/3QBMrCLIvl9KWbkM8tCc1IcBoi5wRccgs2rYOPe1Ueq+/yjEpj1RJzJCAlTFSCUQ9o8msNOkPLRBSzYmw7DhsNMd2xoJDDaUn1/yjE9iWxV+DAKc=
