language: node_js
services:
 - postgresql
node_js: 
 - "5.10.1"
addons:
  postgresql: "9.4"
before_script:
 - bash install.sh
script:
 - source env.sh && npm run test
notifications:
  slack: devops-training-spb:WrZC6AK2axk6c60pHwf0dPlH
